---
info:
  title: Metasploit Vulnerability Emulator
  description: Created by Jin Qian via the GitHub Connector
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/metasploit-vulnerability-emulator
  x-cortex-tag: metasploit-vulnerability-emulator
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
